<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSgxljz5\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSgxljz5/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerSgxljz5.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerSgxljz5\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSgxljz5\appProdProjectContainer([
    'container.build_hash' => 'Sgxljz5',
    'container.build_id' => 'f1a90ea1',
    'container.build_time' => 1642217718,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSgxljz5');
